"""initial graphs and executions

Revision ID: 936ecb44e45c
Revises: 
Create Date: 2026-07-10 14:03:59.887396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '936ecb44e45c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('graph',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('definition', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('graph', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_graph_name'), ['name'], unique=False)

    op.create_table('execution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('graph_id', sa.Integer(), nullable=False),
    sa.Column('graph_version', sa.Integer(), nullable=False),
    sa.Column('definition_snapshot', sa.JSON(), nullable=False),
    sa.Column('thread_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('final_state', sa.JSON(), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['graph_id'], ['graph.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('execution', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_execution_graph_id'), ['graph_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_thread_id'), ['thread_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('execution', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_execution_thread_id'))
        batch_op.drop_index(batch_op.f('ix_execution_graph_id'))

    op.drop_table('execution')
    with op.batch_alter_table('graph', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_graph_name'))

    op.drop_table('graph')
    # ### end Alembic commands ###
